[build]
target = "x86_64-unknown-rinux.json"

[target.'cfg(target_os = "none")']
linker = "rust-lld"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
