[package]
name = "rinux-drivers"
version = "0.2.0"
edition = "2021"
authors = ["Rinux Contributors"]
license = "MIT"

[dependencies]
spin = "0.9"
rinux-kernel = { path = "../kernel" }
rinux-arch-x86 = { path = "../arch/x86" }

[lib]
crate-type = ["rlib"]
